#!/usr/bin/env node
// Reconcile per-session scanner cards into a durable thread registry.
// Reads every threads.*.jsonl in the agent-threads dir (cross-machine),
// clusters sessions by thread_id (repo_key + intent_hash), merges into
// active-threads.jsonl while preserving manual fields, renders
// active-threads.md. Never deletes a thread; stale threads are flagged.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { resolveRegistryDir } from "./lib/paths.mjs";

const home = os.homedir();
const args = parseArgs(process.argv.slice(2));
const dir = path.resolve(
  args.dir ? path.resolve(expandHome(args.dir)) : resolveRegistryDir(),
);
const registryPath = path.join(dir, "active-threads.jsonl");
const boardPath = path.join(dir, "active-threads.md");
const now = Date.now();

// Interim aging thresholds (hours) — staleness p85 per stage from Phase 0.
// Replaced by measured SLEs once the registry records stage transitions.
const STALE_SLE = {
  "Funnel / Triage": 504,
  "On Hold": Infinity,
  "Specify": 312,
  "Plan": 312,
  "Implement": 312,
  "Review / Ship": 72,
  "Done / Archive Candidates": Infinity,
};

// Intent-area tags, order-sensitive (first match wins).
const INTENT_AREAS = [
  ["LinkedIn & Prospecting", /linkedin|prospect|\bcaio\b|connection|dm draft|outreach target|subscriber/],
  ["CRM & Pipeline Data", /hubspot|\bcrm\b|\bfolk\b|\bicp\b|pipeline|import (csv|contact|compan)/],
  ["Podcast", /podcast|episode|show notes/],
  ["Thought Leadership & POV", /\bpov\b|thought leadership|newsletter|provisional|repurpos/],
  ["Content & Publishing", /\bblog\b|syndicat|substack|scrum\.org|post image|content visual|sketchnote|\brss\b|article|transcript/],
  ["Skill Library & Agent Infra", /\bskill\b|adapter|telemetry|\bhook\b|memory|agent|harvest|plan file|thread|session/],
  ["Site & Web", /booking page|website|site copy|blurb|\/meet|page copy|buffer api/],
  ["Meetings & Clients", /meeting|workshop|client|philip/],
  ["Job Search", /job fit|auto-apply|full-time role|job application/],
  ["Sales & Proposals", /proposal|\bsow\b|discovery call|deal/],
];

const STOPWORDS = new Set([
  "the", "and", "for", "with", "this", "that", "can", "you", "your", "out",
  "are", "from", "into", "have", "has", "but", "not", "all", "any", "our",
  "please", "want", "need", "make", "get", "let", "use", "using", "based",
  "give", "show", "find", "help", "should", "would", "could", "what", "how",
  "why", "when", "who", "they", "them", "then", "than", "also", "about",
]);

const ACTIVE_STAGES = ["Specify", "Plan", "Implement", "Review / Ship"];
// Funnel/Triage (maybe-worth-tracking) and On Hold (deliberately parked) are
// shown compact alongside Done, not in the committed-work section.
const QUIET_STAGES = ["Funnel / Triage", "On Hold", "Done / Archive Candidates"];

const cards = loadScanCards(dir);
const existing = loadRegistry(registryPath);
const seen = new Set();
const registry = new Map(existing.map((r) => [r.thread_id, r]));

for (const group of clusterCards(cards)) {
  const memberIds = unique(group.map((c) => c.thread_id)).sort();
  const threadId = memberIds[0]; // deterministic canonical id
  memberIds.forEach((id) => seen.add(id));
  const latest = [...group].sort(byActivityDesc)[0];
  // A prior registry record may sit under any pre-merge member id.
  const prior = memberIds.map((id) => registry.get(id)).find(Boolean);
  // Drop the non-canonical pre-merge records so the cluster has one entry.
  memberIds.slice(1).forEach((id) => registry.delete(id));
  const sessions = dedupeSessions(group);
  const lastActivity = maxDate(group.map((c) => c.last_activity));
  const firstSeen = minDate([
    ...(prior ? [prior.first_seen] : []),
    ...group.map((c) => c.first_activity || c.last_activity),
  ]);
  const inferredStage = latest.stage;
  const manualStage = prior?.manual_stage || null;
  const effectiveStage = manualStage || inferredStage;
  // A stage move counts as a touch — idle time is measured from the later of
  // real session activity and the last manual stage change.
  const stageChangedAt = prior?.stage_changed_at || "";
  const lastTouch = maxDate([lastActivity, stageChangedAt]);
  const staleHours = lastTouch ? (now - Date.parse(lastTouch)) / 3.6e6 : null;

  registry.set(threadId, {
    thread_id: threadId,
    clustered_ids: memberIds,
    repo_key: latest.repo_key,
    intent_hash: latest.intent_hash,
    title: latest.title,
    // Outcome-framed name shown in harness thread lists. Generated by an LLM
    // pass (see set-display-titles.mjs) and preserved across rescans; empty
    // until named, in which case the raw title is used.
    display_title: prior?.display_title || "",
    // Concrete prompt to take the thread one step toward done. Generated by an
    // LLM pass (set-next-steps.mjs); preserved across rescans.
    next_step: prior?.next_step || "",
    outcome_intent: latest.outcome_intent,
    intent_area: prior?.manual_area || intentArea(`${latest.title} ${latest.outcome_intent}`),
    harnesses: unique(group.map((c) => c.harness)).sort(),
    machines: unique(group.map((c) => c.machine)).sort(),
    session_count: sessions.length,
    sessions,
    inferred_stage: inferredStage,
    manual_stage: manualStage,
    stage: effectiveStage,
    stage_changed_at: stageChangedAt,
    blocked: Boolean(latest.blocked),
    status: prior?.manual_status || latest.status,
    tracking_decision: prior?.manual_tracking || latest.tracking_decision,
    // Preserve raw manual_* alongside the derived status/tracking_decision so
    // downstream tools (apply-thread-names archive gate) can read them.
    manual_status: prior?.manual_status,
    manual_tracking: prior?.manual_tracking,
    manual_area: prior?.manual_area,
    where_it_stands: latest.where_it_stands,
    first_seen: firstSeen,
    last_activity: lastActivity,
    total_tool_count: sum(group.map((c) => c.tool_count || 0)),
    staleness_hours: staleHours == null ? null : Math.round(staleHours),
    aging: staleHours != null && staleHours > (STALE_SLE[effectiveStage] ?? Infinity),
    dropped_from_scan: false,
    notes: prior?.notes || "",
    created_at: prior?.created_at || new Date().toISOString(),
    updated_at: new Date().toISOString(),
  });
}

// Threads in the registry but absent from the latest scan window.
for (const [threadId, rec] of registry) {
  if (seen.has(threadId)) continue;
  rec.dropped_from_scan = true;
  const touch = maxDate([rec.last_activity, rec.stage_changed_at]);
  rec.staleness_hours = touch ? Math.round((now - Date.parse(touch)) / 3.6e6) : null;
  rec.aging = touch ? (now - Date.parse(touch)) / 3.6e6 > (STALE_SLE[rec.stage] ?? Infinity) : true;
  rec.updated_at = new Date().toISOString();
  // Heal legacy stage names from earlier taxonomies onto a current stage.
  if (!(rec.stage in STALE_SLE)) rec.stage = "Funnel / Triage";
  if (rec.manual_stage && !(rec.manual_stage in STALE_SLE)) rec.manual_stage = "Funnel / Triage";
}

const records = [...registry.values()].sort(byActivityDesc);
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(registryPath, records.map((r) => JSON.stringify(r)).join("\n") + "\n", "utf8");
fs.writeFileSync(boardPath, renderBoard(records), "utf8");
console.log(`Reconciled ${cards.length} cards into ${records.length} threads -> ${registryPath}`);

function renderBoard(records) {
  const active = records.filter((r) => ACTIVE_STAGES.includes(r.stage));
  const quiet = records.filter((r) => QUIET_STAGES.includes(r.stage));
  const lines = [
    "# Active AI Thread Registry",
    "",
    `Updated: ${new Date().toISOString()}`,
    `Threads: ${records.length} total · ${active.length} active · ${quiet.length} triage/done`,
    "",
    "> Durable registry. `manual_stage`/`manual_status`/`notes` survive rescans;",
    "> activity, staleness, and inferred stage refresh on every reconcile.",
    "> Aging = staleness past the interim Phase 0 staleness SLE for the stage.",
    "",
  ];
  const areaCounts = new Map();
  for (const r of active) areaCounts.set(r.intent_area, (areaCounts.get(r.intent_area) || 0) + 1);
  if (areaCounts.size) {
    lines.push("## Active Threads by Intent Area", "");
    for (const [area, n] of [...areaCounts.entries()].sort((a, b) => b[1] - a[1])) {
      lines.push(`- ${escapeMd(area)} — ${n}`);
    }
    lines.push("");
  }
  lines.push("## Active Threads", "");
  for (const stage of ACTIVE_STAGES) {
    const items = active.filter((r) => r.stage === stage).sort((a, b) => (b.staleness_hours || 0) - (a.staleness_hours || 0));
    if (!items.length) continue;
    lines.push(`### ${stage} (${items.length})`, "");
    for (const r of items) lines.push(...renderThread(r));
  }
  if (!active.length) lines.push("_No active threads._", "");
  lines.push("## Funnel / Triage & Done", "");
  if (!quiet.length) lines.push("_None._", "");
  for (const r of quiet.sort(byActivityDesc)) {
    lines.push(`- ${flag(r)}**${escapeMd(r.display_title || r.title)}** — ${r.stage.split(" / ")[0]} · ${r.harnesses.join("/")} · ${ageLabel(r)}`);
  }
  lines.push("");
  return lines.join("\n").trim() + "\n";
}

function renderThread(r) {
  const out = [
    `#### ${flag(r)}${escapeMd(r.display_title || r.title)}`,
    "",
    `- Thread: \`${r.thread_id}\` · area _${escapeMd(r.intent_area || "Other / Unsorted")}_ · repo \`${r.repo_key}\` · ${r.harnesses.join(", ")}${r.machines.length > 1 ? ` · ${r.machines.length} machines` : ""}`,
    `- Intent: ${escapeMd(truncate(r.outcome_intent, 200))}`,
    `- Standing: ${escapeMd(r.status)} — ${escapeMd(r.where_it_stands)}`,
    `- Tracking: ${r.tracking_decision} · ${ageLabel(r)}${r.manual_stage ? ` · manual stage: ${r.manual_stage}` : ""}`,
  ];
  if (r.notes) out.push(`- Notes: ${escapeMd(r.notes)}`);
  if (r.sessions.length) {
    const s = r.sessions[0];
    out.push(`- Latest session: \`${s.resume || ""}\``);
    if (s.transcript_path) out.push(`  - Open: \`code "${s.transcript_path}"\``);
    if (r.sessions.length > 1) out.push(`  - +${r.sessions.length - 1} earlier session(s) in this thread`);
  }
  out.push("");
  return out;
}

function flag(r) {
  return `${r.blocked ? "[BLOCKED] " : ""}${r.aging ? "[AGING] " : ""}`;
}

function ageLabel(r) {
  if (r.staleness_hours == null) return "age unknown";
  const h = r.staleness_hours;
  const txt = h < 48 ? `${h}h idle` : `${Math.round(h / 24)}d idle`;
  return r.dropped_from_scan ? `${txt} (outside scan window)` : txt;
}

function dedupeSessions(group) {
  const map = new Map();
  for (const c of [...group].sort(byActivityDesc)) {
    const key = `${c.harness}:${c.session_id}`;
    if (!map.has(key)) {
      map.set(key, {
        harness: c.harness,
        machine: c.machine,
        session_id: c.session_id,
        cwd: c.cwd || "",
        transcript_path: c.transcript_path || "",
        resume: c.continue_session || "",
        last_activity: c.last_activity || "",
      });
    }
  }
  return [...map.values()];
}

function loadScanCards(dir) {
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir).filter((f) => /^threads(\.[^.]+)?\.jsonl$/.test(f));
  const machineFiles = files.filter((f) => f !== "threads.jsonl");
  const pick = machineFiles.length ? machineFiles : files; // avoid double-counting the alias
  const cards = [];
  for (const f of pick) {
    for (const row of readJsonl(path.join(dir, f))) {
      if (row && row.thread_id) cards.push(row);
    }
  }
  return cards;
}

function loadRegistry(file) {
  return readJsonl(file).filter((r) => r && r.thread_id);
}

// Lightweight thematic tag for a thread, derived from its intent text.
// Heuristic and order-sensitive (first match wins) — a coarse "what area of
// the business is this" label, not a precise taxonomy.
function intentArea(text) {
  const t = String(text || "").toLowerCase();
  for (const [area, rx] of INTENT_AREAS) if (rx.test(t)) return area;
  return "Other / Unsorted";
}

// Cluster scan cards into logical threads: exact thread_id match, plus a fuzzy
// pass that merges same-repo cards whose intents are clearly similar. This
// catches re-runs of the same intent phrased differently across sessions.
function intentTokens(text) {
  return new Set(
    String(text || "")
      .toLowerCase()
      .replace(/[^a-z0-9 ]+/g, " ")
      .split(/\s+/)
      .filter((t) => t.length > 2 && !STOPWORDS.has(t)),
  );
}

function similarEnough(a, b) {
  if (a.size < 5 || b.size < 5) return false;
  let shared = 0;
  for (const t of a) if (b.has(t)) shared += 1;
  if (shared < 4) return false;
  const jaccard = shared / (a.size + b.size - shared);
  return jaccard >= 0.55;
}

function clusterCards(cards) {
  const parent = cards.map((_, i) => i);
  const find = (i) => (parent[i] === i ? i : (parent[i] = find(parent[i])));
  const union = (a, b) => { parent[find(a)] = find(b); };

  const byId = new Map();
  cards.forEach((c, i) => {
    if (byId.has(c.thread_id)) union(i, byId.get(c.thread_id));
    else byId.set(c.thread_id, i);
  });

  const sig = cards.map((c) => intentTokens(`${c.title} ${c.outcome_intent}`));
  for (let i = 0; i < cards.length; i += 1) {
    for (let j = i + 1; j < cards.length; j += 1) {
      if (cards[i].repo_key !== cards[j].repo_key) continue;
      if (find(i) === find(j)) continue;
      if (similarEnough(sig[i], sig[j])) union(i, j);
    }
  }

  const groups = new Map();
  cards.forEach((c, i) => {
    const root = find(i);
    if (!groups.has(root)) groups.set(root, []);
    groups.get(root).push(c);
  });
  return [...groups.values()];
}

function groupBy(items, keyFn) {
  const map = new Map();
  for (const item of items) {
    const key = keyFn(item);
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(item);
  }
  return map;
}

function byActivityDesc(a, b) {
  return Date.parse(b.last_activity || 0) - Date.parse(a.last_activity || 0);
}

function maxDate(values) {
  const t = values.map((v) => Date.parse(v || 0)).filter((n) => !Number.isNaN(n) && n > 0);
  return t.length ? new Date(Math.max(...t)).toISOString() : "";
}

function minDate(values) {
  const t = values.map((v) => Date.parse(v || 0)).filter((n) => !Number.isNaN(n) && n > 0);
  return t.length ? new Date(Math.min(...t)).toISOString() : "";
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}

function sum(values) {
  return values.reduce((a, b) => a + b, 0);
}

function readJsonl(file) {
  if (!file || !fs.existsSync(file)) return [];
  return fs.readFileSync(file, "utf8").split(/\r?\n/).flatMap((line) => {
    if (!line.trim()) return [];
    try {
      return [JSON.parse(line)];
    } catch {
      return [];
    }
  });
}

function truncate(text, length) {
  const cleaned = String(text || "").replace(/\s+/g, " ").trim();
  return cleaned.length > length ? `${cleaned.slice(0, length - 3)}...` : cleaned;
}

function escapeMd(text) {
  return String(text || "").replace(/\|/g, "\\|");
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i].startsWith("--")) {
      const key = argv[i].slice(2);
      out[key] = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : true;
    }
  }
  return out;
}

function expandHome(value) {
  if (!value) return value;
  if (value === "~") return home;
  if (value.startsWith("~/") || value.startsWith("~\\")) return path.join(home, value.slice(2));
  return value;
}

